/**
 * AlloyForge AI - Master Metallurgical Database & Configurations
 * Embedded Default Catalog (55 Materials, 20 Elements, 15+ Presets)
 */

window.ALLOYFORGE_DEFAULT_DATA = {
    elements: [
    "Cu",
    "Sn",
    "Zn",
    "Pb",
    "Fe",
    "Ni",
    "P",
    "Mn",
    "Si",
    "Al",
    "S",
    "Cr",
    "C",
    "Mg",
    "Ti",
    "Mo",
    "V",
    "Nb",
    "Sb",
    "Ca"
],
    materials: [
    {
        "ID": 1,
        "Name": "BRONZE SCRAP (555)",
        "Cost": 3350.0,
        "Sn": 5.0,
        "Zn": 0.5,
        "Pb": 0.5,
        "Fe": 0.25,
        "Ni": 0.05,
        "P": 0.05,
        "Mn": 0.25,
        "Si": 0.05,
        "Al": 0.25,
        "S": 0.05,
        "Cr": 0.0,
        "C": 0.0,
        "Mg": 0.0,
        "Ti": 0.0,
        "Mo": 0.0,
        "V": 0.0,
        "Nb": 0.0,
        "Sb": 0.0,
        "Ca": 0.0,
        "Cu": 93.05,
        "Material_Name": "BRONZE SCRAP (555)",
        "Cost_Per_Kg": 3350.0,
        "Category": "Copper & Bronze",
        "Max_Stock_Kg": null
    },
    {
        "ID": 2,
        "Name": "Tin Bronze (Sn 9-12)",
        "Cost": 3900.0,
        "Sn": 10.302,
        "Zn": 1.226,
        "Pb": 1.226,
        "Fe": 0.245,
        "Ni": 0.491,
        "P": 0.049,
        "Mn": 0.025,
        "Si": 0.098,
        "Al": 0.245,
        "S": 0.0,
        "Cr": 0.0,
        "C": 0.0,
        "Mg": 0.0,
        "Ti": 0.0,
        "Mo": 0.0,
        "V": 0.0,
        "Nb": 0.0,
        "Sb": 0.0,
        "Ca": 0.0,
        "Cu": 86.093,
        "Material_Name": "Tin Bronze (Sn 9-12)",
        "Cost_Per_Kg": 3900.0,
        "Category": "Copper & Bronze",
        "Max_Stock_Kg": null
    },
    {
        "ID": 3,
        "Name": "BRONZE SHAVINGS",
        "Cost": 2800.0,
        "Sn": 7.519,
        "Zn": 3.055,
        "Pb": 7.049,
        "Fe": 0.47,
        "Ni": 0.94,
        "P": 0.141,
        "Mn": 0.47,
        "Si": 0.235,
        "Al": 0.235,
        "S": 0.0,
        "Cr": 0.0,
        "C": 0.0,
        "Mg": 0.0,
        "Ti": 0.0,
        "Mo": 0.0,
        "V": 0.0,
        "Nb": 0.0,
        "Sb": 0.0,
        "Ca": 0.0,
        "Cu": 79.887,
        "Material_Name": "BRONZE SHAVINGS",
        "Cost_Per_Kg": 2800.0,
        "Category": "Copper & Bronze",
        "Max_Stock_Kg": null
    },
    {
        "ID": 4,
        "Name": "C.I SHELL SCRAP",
        "Cost": 150.0,
        "Sn": 0.0,
        "Zn": 0.0,
        "Pb": 0.0,
        "Fe": 92.075,
        "Ni": 0.5,
        "P": 0.125,
        "Mn": 0.6,
        "Si": 2.0,
        "Al": 0.0,
        "S": 0.05,
        "Cr": 0.6,
        "C": 3.3,
        "Mg": 0.0,
        "Ti": 0.0,
        "Mo": 0.25,
        "V": 0.0,
        "Nb": 0.0,
        "Sb": 0.0,
        "Ca": 0.0,
        "Cu": 0.5,
        "Material_Name": "C.I SHELL SCRAP",
        "Cost_Per_Kg": 150.0,
        "Category": "Cast Iron & Pig Iron",
        "Max_Stock_Kg": null
    },
    {
        "ID": 5,
        "Name": "C.I UNIT SCRAP",
        "Cost": 175.0,
        "Sn": 0.0,
        "Zn": 0.0,
        "Pb": 0.0,
        "Fe": 92.475,
        "Ni": 0.25,
        "P": 0.125,
        "Mn": 0.7,
        "Si": 2.15,
        "Al": 0.0,
        "S": 0.05,
        "Cr": 0.3,
        "C": 3.4,
        "Mg": 0.0,
        "Ti": 0.0,
        "Mo": 0.15,
        "V": 0.0,
        "Nb": 0.0,
        "Sb": 0.0,
        "Ca": 0.0,
        "Cu": 0.4,
        "Material_Name": "C.I UNIT SCRAP",
        "Cost_Per_Kg": 175.0,
        "Category": "Cast Iron & Pig Iron",
        "Max_Stock_Kg": null
    },
    {
        "ID": 6,
        "Name": "CI  SCRAP - MISC",
        "Cost": 167.0,
        "Sn": 0.0,
        "Zn": 0.0,
        "Pb": 0.0,
        "Fe": 92.475,
        "Ni": 0.25,
        "P": 0.125,
        "Mn": 0.7,
        "Si": 2.15,
        "Al": 0.0,
        "S": 0.05,
        "Cr": 0.3,
        "C": 3.4,
        "Mg": 0.0,
        "Ti": 0.0,
        "Mo": 0.15,
        "V": 0.0,
        "Nb": 0.0,
        "Sb": 0.0,
        "Ca": 0.0,
        "Cu": 0.4,
        "Material_Name": "CI  SCRAP - MISC",
        "Cost_Per_Kg": 167.0,
        "Category": "Cast Iron & Pig Iron",
        "Max_Stock_Kg": null
    },
    {
        "ID": 7,
        "Name": "COPPER SCRAP",
        "Cost": 3550.0,
        "Sn": 0.0,
        "Zn": 0.0,
        "Pb": 0.0,
        "Fe": 0.0,
        "Ni": 0.0,
        "P": 0.0,
        "Mn": 0.0,
        "Si": 0.0,
        "Al": 0.0,
        "S": 0.0,
        "Cr": 0.0,
        "C": 0.0,
        "Mg": 0.0,
        "Ti": 0.0,
        "Mo": 0.0,
        "V": 0.0,
        "Nb": 0.0,
        "Sb": 0.0,
        "Ca": 0.0,
        "Cu": 98.4,
        "Material_Name": "COPPER SCRAP",
        "Cost_Per_Kg": 3550.0,
        "Category": "Copper & Bronze",
        "Max_Stock_Kg": null
    },
    {
        "ID": 8,
        "Name": "DIE STEEL SCRAP \u2015 H-13",
        "Cost": 250.0,
        "Sn": 0.0,
        "Zn": 0.0,
        "Pb": 0.0,
        "Fe": 91.765,
        "Ni": 0.25,
        "P": 0.0,
        "Mn": 0.35,
        "Si": 1.0,
        "Al": 0.0,
        "S": 0.0,
        "Cr": 5.125,
        "C": 0.385,
        "Mg": 0.0,
        "Ti": 0.0,
        "Mo": 0.0,
        "V": 1.0,
        "Nb": 0.0,
        "Sb": 0.0,
        "Ca": 0.0,
        "Cu": 0.125,
        "Material_Name": "DIE STEEL SCRAP \u2015 H-13",
        "Cost_Per_Kg": 250.0,
        "Category": "Carbon & Special Steel",
        "Max_Stock_Kg": null
    },
    {
        "ID": 9,
        "Name": "GRINDING MEDIA SCRAP",
        "Cost": 190.0,
        "Sn": 0.0,
        "Zn": 0.0,
        "Pb": 0.0,
        "Fe": 95.4,
        "Ni": 0.5,
        "P": 0.0,
        "Mn": 1.0,
        "Si": 0.7,
        "Al": 0.0,
        "S": 0.0,
        "Cr": 1.25,
        "C": 0.9,
        "Mg": 0.0,
        "Ti": 0.0,
        "Mo": 0.25,
        "V": 0.0,
        "Nb": 0.0,
        "Sb": 0.0,
        "Ca": 0.0,
        "Cu": 0.0,
        "Material_Name": "GRINDING MEDIA SCRAP",
        "Cost_Per_Kg": 190.0,
        "Category": "Carbon & Special Steel",
        "Max_Stock_Kg": null
    },
    {
        "ID": 10,
        "Name": "HIGH CHROME SCRAP 25%",
        "Cost": 260.0,
        "Sn": 0.0,
        "Zn": 0.0,
        "Pb": 0.0,
        "Fe": 68.6,
        "Ni": 0.5,
        "P": 0.0,
        "Mn": 0.9,
        "Si": 1.25,
        "Al": 0.0,
        "S": 0.0,
        "Cr": 25.0,
        "C": 2.5,
        "Mg": 0.0,
        "Ti": 0.0,
        "Mo": 0.75,
        "V": 0.0,
        "Nb": 0.0,
        "Sb": 0.0,
        "Ca": 0.0,
        "Cu": 0.5,
        "Material_Name": "HIGH CHROME SCRAP 25%",
        "Cost_Per_Kg": 260.0,
        "Category": "Carbon & Special Steel",
        "Max_Stock_Kg": null
    },
    {
        "ID": 11,
        "Name": "KANSI SCRAP",
        "Cost": 4100.0,
        "Sn": 0.493,
        "Zn": 36.982,
        "Pb": 0.986,
        "Fe": 0.247,
        "Ni": 0.493,
        "P": 0.0,
        "Mn": 0.0,
        "Si": 0.148,
        "Al": 0.0,
        "S": 0.0,
        "Cr": 0.0,
        "C": 0.0,
        "Mg": 0.0,
        "Ti": 0.0,
        "Mo": 0.0,
        "V": 0.0,
        "Nb": 0.0,
        "Sb": 0.0,
        "Ca": 0.0,
        "Cu": 60.651,
        "Material_Name": "KANSI SCRAP",
        "Cost_Per_Kg": 4100.0,
        "Category": "Copper & Bronze",
        "Max_Stock_Kg": null
    },
    {
        "ID": 12,
        "Name": "M.S SCRAP",
        "Cost": 168.0,
        "Sn": 0.0,
        "Zn": 0.0,
        "Pb": 0.0,
        "Fe": 98.535,
        "Ni": 0.15,
        "P": 0.025,
        "Mn": 0.65,
        "Si": 0.2,
        "Al": 0.0,
        "S": 0.025,
        "Cr": 0.0,
        "C": 0.165,
        "Mg": 0.0,
        "Ti": 0.0,
        "Mo": 0.05,
        "V": 0.0,
        "Nb": 0.0,
        "Sb": 0.0,
        "Ca": 0.0,
        "Cu": 0.2,
        "Material_Name": "M.S SCRAP",
        "Cost_Per_Kg": 168.0,
        "Category": "Carbon & Special Steel",
        "Max_Stock_Kg": null
    },
    {
        "ID": 13,
        "Name": "M.S SCRAP \u2015 DEEP DRAWN",
        "Cost": 174.0,
        "Sn": 0.0,
        "Zn": 0.0,
        "Pb": 0.0,
        "Fe": 98.875,
        "Ni": 0.1,
        "P": 0.0,
        "Mn": 0.5,
        "Si": 0.15,
        "Al": 0.0,
        "S": 0.0,
        "Cr": 0.1,
        "C": 0.1,
        "Mg": 0.0,
        "Ti": 0.0,
        "Mo": 0.025,
        "V": 0.0,
        "Nb": 0.0,
        "Sb": 0.0,
        "Ca": 0.0,
        "Cu": 0.15,
        "Material_Name": "M.S SCRAP \u2015 DEEP DRAWN",
        "Cost_Per_Kg": 174.0,
        "Category": "Carbon & Special Steel",
        "Max_Stock_Kg": null
    },
    {
        "ID": 14,
        "Name": "M.S SHAVING",
        "Cost": 150.0,
        "Sn": 0.0,
        "Zn": 0.0,
        "Pb": 0.0,
        "Fe": 98.535,
        "Ni": 0.15,
        "P": 0.025,
        "Mn": 0.65,
        "Si": 0.2,
        "Al": 0.0,
        "S": 0.025,
        "Cr": 0.0,
        "C": 0.165,
        "Mg": 0.0,
        "Ti": 0.0,
        "Mo": 0.05,
        "V": 0.0,
        "Nb": 0.0,
        "Sb": 0.0,
        "Ca": 0.0,
        "Cu": 0.2,
        "Material_Name": "M.S SHAVING",
        "Cost_Per_Kg": 150.0,
        "Category": "Carbon & Special Steel",
        "Max_Stock_Kg": null
    },
    {
        "ID": 15,
        "Name": "MANGANESE STEEL SCRAP 12%",
        "Cost": 220.0,
        "Sn": 0.0,
        "Zn": 0.0,
        "Pb": 0.0,
        "Fe": 83.5,
        "Ni": 0.5,
        "P": 0.0,
        "Mn": 12.5,
        "Si": 0.65,
        "Al": 0.0,
        "S": 0.0,
        "Cr": 1.0,
        "C": 1.1,
        "Mg": 0.0,
        "Ti": 0.0,
        "Mo": 0.25,
        "V": 0.0,
        "Nb": 0.0,
        "Sb": 0.0,
        "Ca": 0.0,
        "Cu": 0.5,
        "Material_Name": "MANGANESE STEEL SCRAP 12%",
        "Cost_Per_Kg": 220.0,
        "Category": "Carbon & Special Steel",
        "Max_Stock_Kg": null
    },
    {
        "ID": 16,
        "Name": "MANGANESE STEEL SCRAP (12-18% Mn)",
        "Cost": 178.0,
        "Sn": 0.0,
        "Zn": 0.0,
        "Pb": 0.0,
        "Fe": 80.7,
        "Ni": 0.5,
        "P": 0.0,
        "Mn": 15.0,
        "Si": 0.65,
        "Al": 0.0,
        "S": 0.0,
        "Cr": 1.25,
        "C": 1.15,
        "Mg": 0.0,
        "Ti": 0.0,
        "Mo": 0.25,
        "V": 0.0,
        "Nb": 0.0,
        "Sb": 0.0,
        "Ca": 0.0,
        "Cu": 0.5,
        "Material_Name": "MANGANESE STEEL SCRAP (12-18% Mn)",
        "Cost_Per_Kg": 178.0,
        "Category": "Carbon & Special Steel",
        "Max_Stock_Kg": null
    },
    {
        "ID": 17,
        "Name": "PIG IRON \u2015 IMPORTED",
        "Cost": 250.0,
        "Sn": 0.0,
        "Zn": 0.0,
        "Pb": 0.0,
        "Fe": 93.75,
        "Ni": 0.1,
        "P": 0.0,
        "Mn": 0.6,
        "Si": 1.25,
        "Al": 0.0,
        "S": 0.0,
        "Cr": 0.1,
        "C": 4.0,
        "Mg": 0.0,
        "Ti": 0.0,
        "Mo": 0.05,
        "V": 0.0,
        "Nb": 0.0,
        "Sb": 0.0,
        "Ca": 0.0,
        "Cu": 0.15,
        "Material_Name": "PIG IRON \u2015 IMPORTED",
        "Cost_Per_Kg": 250.0,
        "Category": "Cast Iron & Pig Iron",
        "Max_Stock_Kg": null
    },
    {
        "ID": 18,
        "Name": "PIG IRON \u2015 LOCAL",
        "Cost": 190.0,
        "Sn": 0.0,
        "Zn": 0.0,
        "Pb": 0.0,
        "Fe": 93.25,
        "Ni": 0.1,
        "P": 0.0,
        "Mn": 0.6,
        "Si": 1.75,
        "Al": 0.0,
        "S": 0.0,
        "Cr": 0.1,
        "C": 4.0,
        "Mg": 0.0,
        "Ti": 0.0,
        "Mo": 0.05,
        "V": 0.0,
        "Nb": 0.0,
        "Sb": 0.0,
        "Ca": 0.0,
        "Cu": 0.15,
        "Material_Name": "PIG IRON \u2015 LOCAL",
        "Cost_Per_Kg": 190.0,
        "Category": "Cast Iron & Pig Iron",
        "Max_Stock_Kg": null
    },
    {
        "ID": 19,
        "Name": "S.S SCRAP 201",
        "Cost": 155.0,
        "Sn": 0.0,
        "Zn": 0.0,
        "Pb": 0.0,
        "Fe": 69.675,
        "Ni": 4.5,
        "P": 0.0,
        "Mn": 6.5,
        "Si": 0.0,
        "Al": 0.0,
        "S": 0.0,
        "Cr": 17.0,
        "C": 0.075,
        "Mg": 0.0,
        "Ti": 0.0,
        "Mo": 0.25,
        "V": 0.0,
        "Nb": 0.0,
        "Sb": 0.0,
        "Ca": 0.0,
        "Cu": 2.0,
        "Material_Name": "S.S SCRAP 201",
        "Cost_Per_Kg": 155.0,
        "Category": "Stainless & High Alloy",
        "Max_Stock_Kg": null
    },
    {
        "ID": 20,
        "Name": "S.S SCRAP 26/12 (SS 309)",
        "Cost": 620.0,
        "Sn": 0.0,
        "Zn": 0.0,
        "Pb": 0.0,
        "Fe": 61.373,
        "Ni": 12.0,
        "P": 0.022,
        "Mn": 1.25,
        "Si": 1.0,
        "Al": 0.0,
        "S": 0.015,
        "Cr": 24.0,
        "C": 0.09,
        "Mg": 0.0,
        "Ti": 0.0,
        "Mo": 0.25,
        "V": 0.0,
        "Nb": 0.0,
        "Sb": 0.0,
        "Ca": 0.0,
        "Cu": 0.0,
        "Material_Name": "S.S SCRAP 26/12 (SS 309)",
        "Cost_Per_Kg": 620.0,
        "Category": "Stainless & High Alloy",
        "Max_Stock_Kg": null
    },
    {
        "ID": 21,
        "Name": "S.S SCRAP 26/20 (SS 310)",
        "Cost": 920.0,
        "Sn": 0.0,
        "Zn": 0.0,
        "Pb": 0.0,
        "Fe": 51.873,
        "Ni": 20.5,
        "P": 0.022,
        "Mn": 1.25,
        "Si": 1.0,
        "Al": 0.0,
        "S": 0.015,
        "Cr": 25.0,
        "C": 0.09,
        "Mg": 0.0,
        "Ti": 0.0,
        "Mo": 0.25,
        "V": 0.0,
        "Nb": 0.0,
        "Sb": 0.0,
        "Ca": 0.0,
        "Cu": 0.0,
        "Material_Name": "S.S SCRAP 26/20 (SS 310)",
        "Cost_Per_Kg": 920.0,
        "Category": "Stainless & High Alloy",
        "Max_Stock_Kg": null
    },
    {
        "ID": 22,
        "Name": "S.S SCRAP 26/4",
        "Cost": 300.0,
        "Sn": 0.0,
        "Zn": 0.0,
        "Pb": 0.0,
        "Fe": 68.278,
        "Ni": 4.0,
        "P": 0.002,
        "Mn": 1.0,
        "Si": 0.65,
        "Al": 0.0,
        "S": 0.015,
        "Cr": 25.5,
        "C": 0.055,
        "Mg": 0.0,
        "Ti": 0.0,
        "Mo": 0.5,
        "V": 0.0,
        "Nb": 0.0,
        "Sb": 0.0,
        "Ca": 0.0,
        "Cu": 0.0,
        "Material_Name": "S.S SCRAP 26/4",
        "Cost_Per_Kg": 300.0,
        "Category": "Stainless & High Alloy",
        "Max_Stock_Kg": null
    },
    {
        "ID": 23,
        "Name": "S.S SCRAP 304",
        "Cost": 350.0,
        "Sn": 0.0,
        "Zn": 0.0,
        "Pb": 0.0,
        "Fe": 69.423,
        "Ni": 9.25,
        "P": 0.022,
        "Mn": 1.0,
        "Si": 0.5,
        "Al": 0.0,
        "S": 0.015,
        "Cr": 19.0,
        "C": 0.04,
        "Mg": 0.0,
        "Ti": 0.0,
        "Mo": 0.25,
        "V": 0.0,
        "Nb": 0.0,
        "Sb": 0.0,
        "Ca": 0.0,
        "Cu": 0.5,
        "Material_Name": "S.S SCRAP 304",
        "Cost_Per_Kg": 350.0,
        "Category": "Stainless & High Alloy",
        "Max_Stock_Kg": null
    },
    {
        "ID": 24,
        "Name": "S.S SCRAP 316",
        "Cost": 750.0,
        "Sn": 0.0,
        "Zn": 0.0,
        "Pb": 0.0,
        "Fe": 66.423,
        "Ni": 12.0,
        "P": 0.022,
        "Mn": 1.0,
        "Si": 0.5,
        "Al": 0.0,
        "S": 0.015,
        "Cr": 17.0,
        "C": 0.04,
        "Mg": 0.0,
        "Ti": 0.0,
        "Mo": 2.5,
        "V": 0.0,
        "Nb": 0.0,
        "Sb": 0.0,
        "Ca": 0.0,
        "Cu": 0.5,
        "Material_Name": "S.S SCRAP 316",
        "Cost_Per_Kg": 750.0,
        "Category": "Stainless & High Alloy",
        "Max_Stock_Kg": null
    },
    {
        "ID": 25,
        "Name": "S.S SCRAP 420",
        "Cost": 190.0,
        "Sn": 0.0,
        "Zn": 0.0,
        "Pb": 0.0,
        "Fe": 84.815,
        "Ni": 0.375,
        "P": 0.02,
        "Mn": 0.5,
        "Si": 0.5,
        "Al": 0.0,
        "S": 0.015,
        "Cr": 13.0,
        "C": 0.275,
        "Mg": 0.0,
        "Ti": 0.0,
        "Mo": 0.25,
        "V": 0.0,
        "Nb": 0.0,
        "Sb": 0.0,
        "Ca": 0.0,
        "Cu": 0.25,
        "Material_Name": "S.S SCRAP 420",
        "Cost_Per_Kg": 190.0,
        "Category": "Stainless & High Alloy",
        "Max_Stock_Kg": null
    },
    {
        "ID": 26,
        "Name": "S.S SCRAP 430",
        "Cost": 240.0,
        "Sn": 0.0,
        "Zn": 0.0,
        "Pb": 0.0,
        "Fe": 81.03,
        "Ni": 0.375,
        "P": 0.02,
        "Mn": 0.5,
        "Si": 0.5,
        "Al": 0.0,
        "S": 0.015,
        "Cr": 17.0,
        "C": 0.06,
        "Mg": 0.0,
        "Ti": 0.0,
        "Mo": 0.25,
        "V": 0.0,
        "Nb": 0.0,
        "Sb": 0.0,
        "Ca": 0.0,
        "Cu": 0.25,
        "Material_Name": "S.S SCRAP 430",
        "Cost_Per_Kg": 240.0,
        "Category": "Stainless & High Alloy",
        "Max_Stock_Kg": null
    },
    {
        "ID": 27,
        "Name": "SG IRON SCRAP",
        "Cost": 165.0,
        "Sn": 0.05,
        "Zn": 0.0,
        "Pb": 0.0,
        "Fe": 93.335,
        "Ni": 0.0,
        "P": 0.0,
        "Mn": 0.45,
        "Si": 2.4,
        "Al": 0.0,
        "S": 0.0,
        "Cr": 0.075,
        "C": 3.5,
        "Mg": 0.04,
        "Ti": 0.0,
        "Mo": 0.15,
        "V": 0.0,
        "Nb": 0.0,
        "Sb": 0.0,
        "Ca": 0.0,
        "Cu": 0.0,
        "Material_Name": "SG IRON SCRAP",
        "Cost_Per_Kg": 165.0,
        "Category": "Cast Iron & Pig Iron",
        "Max_Stock_Kg": null
    },
    {
        "ID": 28,
        "Name": "C.I SHAVING",
        "Cost": 150.0,
        "Sn": 0.0,
        "Zn": 0.0,
        "Pb": 0.0,
        "Fe": 92.475,
        "Ni": 0.25,
        "P": 0.125,
        "Mn": 0.7,
        "Si": 2.15,
        "Al": 0.0,
        "S": 0.05,
        "Cr": 0.3,
        "C": 3.4,
        "Mg": 0.0,
        "Ti": 0.0,
        "Mo": 0.15,
        "V": 0.0,
        "Nb": 0.0,
        "Sb": 0.0,
        "Ca": 0.0,
        "Cu": 0.4,
        "Material_Name": "C.I SHAVING",
        "Cost_Per_Kg": 150.0,
        "Category": "Cast Iron & Pig Iron",
        "Max_Stock_Kg": null
    },
    {
        "ID": 29,
        "Name": "S.S SHAVING (304)",
        "Cost": 220.0,
        "Sn": 0.0,
        "Zn": 0.0,
        "Pb": 0.0,
        "Fe": 69.423,
        "Ni": 9.25,
        "P": 0.022,
        "Mn": 1.0,
        "Si": 0.5,
        "Al": 0.0,
        "S": 0.015,
        "Cr": 19.0,
        "C": 0.04,
        "Mg": 0.0,
        "Ti": 0.0,
        "Mo": 0.25,
        "V": 0.0,
        "Nb": 0.0,
        "Sb": 0.0,
        "Ca": 0.0,
        "Cu": 0.5,
        "Material_Name": "S.S SHAVING (304)",
        "Cost_Per_Kg": 220.0,
        "Category": "Stainless & High Alloy",
        "Max_Stock_Kg": null
    },
    {
        "ID": 30,
        "Name": "ALUMINIUM SCRAP",
        "Cost": 730.0,
        "Sn": 0.0,
        "Zn": 0.275,
        "Pb": 0.0,
        "Fe": 0.65,
        "Ni": 0.0,
        "P": 0.0,
        "Mn": 0.275,
        "Si": 1.0,
        "Al": 97.15,
        "S": 0.0,
        "Cr": 0.0,
        "C": 0.0,
        "Mg": 0.275,
        "Ti": 0.075,
        "Mo": 0.0,
        "V": 0.0,
        "Nb": 0.0,
        "Sb": 0.0,
        "Ca": 0.0,
        "Cu": 0.3,
        "Material_Name": "ALUMINIUM SCRAP",
        "Cost_Per_Kg": 730.0,
        "Category": "Virgin Metals & Additives",
        "Max_Stock_Kg": null
    },
    {
        "ID": 31,
        "Name": "ANTIMONY",
        "Cost": 18000.0,
        "Sn": 0.0,
        "Zn": 0.0,
        "Pb": 0.0,
        "Fe": 0.0,
        "Ni": 0.0,
        "P": 0.0,
        "Mn": 0.0,
        "Si": 0.0,
        "Al": 0.0,
        "S": 0.0,
        "Cr": 0.0,
        "C": 0.0,
        "Mg": 0.0,
        "Ti": 0.0,
        "Mo": 0.0,
        "V": 0.0,
        "Nb": 0.0,
        "Sb": 99.5,
        "Ca": 0.0,
        "Cu": 0.0,
        "Material_Name": "ANTIMONY",
        "Cost_Per_Kg": 18000.0,
        "Category": "Virgin Metals & Additives",
        "Max_Stock_Kg": null
    },
    {
        "ID": 32,
        "Name": "CALCIUM SILICON",
        "Cost": 562.0,
        "Sn": 0.0,
        "Zn": 0.0,
        "Pb": 0.0,
        "Fe": 8.5,
        "Ni": 0.0,
        "P": 0.0,
        "Mn": 0.0,
        "Si": 60.0,
        "Al": 1.5,
        "S": 0.0,
        "Cr": 0.0,
        "C": 0.0,
        "Mg": 0.0,
        "Ti": 0.0,
        "Mo": 0.0,
        "V": 0.0,
        "Nb": 0.0,
        "Sb": 0.0,
        "Ca": 30.0,
        "Cu": 0.0,
        "Material_Name": "CALCIUM SILICON",
        "Cost_Per_Kg": 562.0,
        "Category": "Ferro Alloys",
        "Max_Stock_Kg": null
    },
    {
        "ID": 33,
        "Name": "CARBON POWDER",
        "Cost": 181.0,
        "Sn": 0.0,
        "Zn": 0.0,
        "Pb": 0.0,
        "Fe": 0.0,
        "Ni": 0.0,
        "P": 0.0,
        "Mn": 0.0,
        "Si": 0.0,
        "Al": 0.0,
        "S": 0.0,
        "Cr": 0.0,
        "C": 98.75,
        "Mg": 0.0,
        "Ti": 0.0,
        "Mo": 0.0,
        "V": 0.0,
        "Nb": 0.0,
        "Sb": 0.0,
        "Ca": 0.0,
        "Cu": 0.0,
        "Material_Name": "CARBON POWDER",
        "Cost_Per_Kg": 181.0,
        "Category": "Virgin Metals & Additives",
        "Max_Stock_Kg": null
    },
    {
        "ID": 34,
        "Name": "COPPER PHOSPHORUS",
        "Cost": 3575.0,
        "Sn": 0.0,
        "Zn": 0.0,
        "Pb": 0.0,
        "Fe": 0.0,
        "Ni": 0.0,
        "P": 15.0,
        "Mn": 0.0,
        "Si": 0.0,
        "Al": 0.0,
        "S": 0.0,
        "Cr": 0.0,
        "C": 0.0,
        "Mg": 0.0,
        "Ti": 0.0,
        "Mo": 0.0,
        "V": 0.0,
        "Nb": 0.0,
        "Sb": 0.0,
        "Ca": 0.0,
        "Cu": 85.0,
        "Material_Name": "COPPER PHOSPHORUS",
        "Cost_Per_Kg": 3575.0,
        "Category": "Copper & Bronze",
        "Max_Stock_Kg": null
    },
    {
        "ID": 35,
        "Name": "COPPER PIPE",
        "Cost": 5000.0,
        "Sn": 0.0,
        "Zn": 0.0,
        "Pb": 0.0,
        "Fe": 0.0,
        "Ni": 0.0,
        "P": 0.0,
        "Mn": 0.0,
        "Si": 0.0,
        "Al": 0.0,
        "S": 0.0,
        "Cr": 0.0,
        "C": 0.0,
        "Mg": 0.0,
        "Ti": 0.0,
        "Mo": 0.0,
        "V": 0.0,
        "Nb": 0.0,
        "Sb": 0.0,
        "Ca": 0.0,
        "Cu": 99.5,
        "Material_Name": "COPPER PIPE",
        "Cost_Per_Kg": 5000.0,
        "Category": "Copper & Bronze",
        "Max_Stock_Kg": null
    },
    {
        "ID": 36,
        "Name": "FERRO CHROME \u2015 HIGH CARBON",
        "Cost": 510.0,
        "Sn": 0.0,
        "Zn": 0.0,
        "Pb": 0.0,
        "Fe": 24.75,
        "Ni": 0.0,
        "P": 0.0,
        "Mn": 0.75,
        "Si": 2.0,
        "Al": 0.0,
        "S": 0.0,
        "Cr": 65.0,
        "C": 7.5,
        "Mg": 0.0,
        "Ti": 0.0,
        "Mo": 0.0,
        "V": 0.0,
        "Nb": 0.0,
        "Sb": 0.0,
        "Ca": 0.0,
        "Cu": 0.0,
        "Material_Name": "FERRO CHROME \u2015 HIGH CARBON",
        "Cost_Per_Kg": 510.0,
        "Category": "Ferro Alloys",
        "Max_Stock_Kg": null
    },
    {
        "ID": 37,
        "Name": "FERRO CHROME \u2015 LOW CARBON",
        "Cost": 801.0,
        "Sn": 0.0,
        "Zn": 0.0,
        "Pb": 0.0,
        "Fe": 32.185,
        "Ni": 0.0,
        "P": 0.0,
        "Mn": 0.75,
        "Si": 2.0,
        "Al": 0.0,
        "S": 0.0,
        "Cr": 65.0,
        "C": 0.065,
        "Mg": 0.0,
        "Ti": 0.0,
        "Mo": 0.0,
        "V": 0.0,
        "Nb": 0.0,
        "Sb": 0.0,
        "Ca": 0.0,
        "Cu": 0.0,
        "Material_Name": "FERRO CHROME \u2015 LOW CARBON",
        "Cost_Per_Kg": 801.0,
        "Category": "Ferro Alloys",
        "Max_Stock_Kg": null
    },
    {
        "ID": 38,
        "Name": "FERRO MANGANESE \u2015 HIGH CARBON",
        "Cost": 320.0,
        "Sn": 0.0,
        "Zn": 0.0,
        "Pb": 0.0,
        "Fe": 16.5,
        "Ni": 0.0,
        "P": 0.0,
        "Mn": 75.0,
        "Si": 1.5,
        "Al": 0.0,
        "S": 0.0,
        "Cr": 0.0,
        "C": 7.0,
        "Mg": 0.0,
        "Ti": 0.0,
        "Mo": 0.0,
        "V": 0.0,
        "Nb": 0.0,
        "Sb": 0.0,
        "Ca": 0.0,
        "Cu": 0.0,
        "Material_Name": "FERRO MANGANESE \u2015 HIGH CARBON",
        "Cost_Per_Kg": 320.0,
        "Category": "Ferro Alloys",
        "Max_Stock_Kg": null
    },
    {
        "ID": 39,
        "Name": "FERRO MANGANESE \u2015 LOW CARBON",
        "Cost": 850.0,
        "Sn": 0.0,
        "Zn": 0.0,
        "Pb": 0.0,
        "Fe": 17.5,
        "Ni": 0.0,
        "P": 0.0,
        "Mn": 80.0,
        "Si": 1.5,
        "Al": 0.0,
        "S": 0.0,
        "Cr": 0.0,
        "C": 1.0,
        "Mg": 0.0,
        "Ti": 0.0,
        "Mo": 0.0,
        "V": 0.0,
        "Nb": 0.0,
        "Sb": 0.0,
        "Ca": 0.0,
        "Cu": 0.0,
        "Material_Name": "FERRO MANGANESE \u2015 LOW CARBON",
        "Cost_Per_Kg": 850.0,
        "Category": "Ferro Alloys",
        "Max_Stock_Kg": null
    },
    {
        "ID": 40,
        "Name": "FERRO MOLY - 60 %",
        "Cost": 10000.0,
        "Sn": 0.0,
        "Zn": 0.0,
        "Pb": 0.0,
        "Fe": 37.0,
        "Ni": 0.0,
        "P": 0.0,
        "Mn": 0.0,
        "Si": 1.5,
        "Al": 0.0,
        "S": 0.0,
        "Cr": 0.0,
        "C": 0.0,
        "Mg": 0.0,
        "Ti": 0.0,
        "Mo": 61.5,
        "V": 0.0,
        "Nb": 0.0,
        "Sb": 0.0,
        "Ca": 0.0,
        "Cu": 0.0,
        "Material_Name": "FERRO MOLY - 60 %",
        "Cost_Per_Kg": 10000.0,
        "Category": "Ferro Alloys",
        "Max_Stock_Kg": null
    },
    {
        "ID": 41,
        "Name": "FERRO MOLY- 100 %",
        "Cost": 12500.0,
        "Sn": 0.0,
        "Zn": 0.0,
        "Pb": 0.0,
        "Fe": 0.0,
        "Ni": 0.0,
        "P": 0.0,
        "Mn": 0.0,
        "Si": 0.0,
        "Al": 0.0,
        "S": 0.0,
        "Cr": 0.0,
        "C": 0.0,
        "Mg": 0.0,
        "Ti": 0.0,
        "Mo": 99.5,
        "V": 0.0,
        "Nb": 0.0,
        "Sb": 0.0,
        "Ca": 0.0,
        "Cu": 0.0,
        "Material_Name": "FERRO MOLY- 100 %",
        "Cost_Per_Kg": 12500.0,
        "Category": "Ferro Alloys",
        "Max_Stock_Kg": null
    },
    {
        "ID": 42,
        "Name": "FERRO NIOBIUM POWDER",
        "Cost": 20000.0,
        "Sn": 0.0,
        "Zn": 0.0,
        "Pb": 0.0,
        "Fe": 30.15,
        "Ni": 0.0,
        "P": 0.0,
        "Mn": 0.0,
        "Si": 2.0,
        "Al": 1.75,
        "S": 0.0,
        "Cr": 0.0,
        "C": 0.3,
        "Mg": 0.0,
        "Ti": 0.8,
        "Mo": 0.0,
        "V": 0.0,
        "Nb": 65.0,
        "Sb": 0.0,
        "Ca": 0.0,
        "Cu": 0.0,
        "Material_Name": "FERRO NIOBIUM POWDER",
        "Cost_Per_Kg": 20000.0,
        "Category": "Ferro Alloys",
        "Max_Stock_Kg": null
    },
    {
        "ID": 43,
        "Name": "FERRO PHOSPHORUS",
        "Cost": 400.0,
        "Sn": 0.0,
        "Zn": 0.0,
        "Pb": 0.0,
        "Fe": 74.25,
        "Ni": 0.0,
        "P": 22.5,
        "Mn": 1.25,
        "Si": 2.0,
        "Al": 0.0,
        "S": 0.0,
        "Cr": 0.0,
        "C": 0.0,
        "Mg": 0.0,
        "Ti": 0.0,
        "Mo": 0.0,
        "V": 0.0,
        "Nb": 0.0,
        "Sb": 0.0,
        "Ca": 0.0,
        "Cu": 0.0,
        "Material_Name": "FERRO PHOSPHORUS",
        "Cost_Per_Kg": 400.0,
        "Category": "Ferro Alloys",
        "Max_Stock_Kg": null
    },
    {
        "ID": 44,
        "Name": "FERRO SILICON",
        "Cost": 390.0,
        "Sn": 0.0,
        "Zn": 0.0,
        "Pb": 0.0,
        "Fe": 25.0,
        "Ni": 0.0,
        "P": 0.0,
        "Mn": 0.0,
        "Si": 75.0,
        "Al": 0.0,
        "S": 0.0,
        "Cr": 0.0,
        "C": 0.0,
        "Mg": 0.0,
        "Ti": 0.0,
        "Mo": 0.0,
        "V": 0.0,
        "Nb": 0.0,
        "Sb": 0.0,
        "Ca": 0.0,
        "Cu": 0.0,
        "Material_Name": "FERRO SILICON",
        "Cost_Per_Kg": 390.0,
        "Category": "Ferro Alloys",
        "Max_Stock_Kg": null
    },
    {
        "ID": 45,
        "Name": "FERRO TITANIUM",
        "Cost": 1000.0,
        "Sn": 0.0,
        "Zn": 0.0,
        "Pb": 0.0,
        "Fe": 65.5,
        "Ni": 0.0,
        "P": 0.0,
        "Mn": 0.75,
        "Si": 1.25,
        "Al": 0.0,
        "S": 0.0,
        "Cr": 0.0,
        "C": 0.0,
        "Mg": 0.0,
        "Ti": 32.5,
        "Mo": 0.0,
        "V": 0.0,
        "Nb": 0.0,
        "Sb": 0.0,
        "Ca": 0.0,
        "Cu": 0.0,
        "Material_Name": "FERRO TITANIUM",
        "Cost_Per_Kg": 1000.0,
        "Category": "Ferro Alloys",
        "Max_Stock_Kg": null
    },
    {
        "ID": 46,
        "Name": "FERRO VANIDIUM",
        "Cost": 15000.0,
        "Sn": 1.25,
        "Zn": 0.0,
        "Pb": 0.0,
        "Fe": 17.7,
        "Ni": 0.0,
        "P": 0.0,
        "Mn": 0.75,
        "Si": 0.0,
        "Al": 0.0,
        "S": 0.0,
        "Cr": 0.0,
        "C": 0.3,
        "Mg": 0.0,
        "Ti": 0.0,
        "Mo": 0.0,
        "V": 80.0,
        "Nb": 0.0,
        "Sb": 0.0,
        "Ca": 0.0,
        "Cu": 0.0,
        "Material_Name": "FERRO VANIDIUM",
        "Cost_Per_Kg": 15000.0,
        "Category": "Ferro Alloys",
        "Max_Stock_Kg": null
    },
    {
        "ID": 47,
        "Name": "LEAD",
        "Cost": 690.0,
        "Sn": 0.0,
        "Zn": 0.0,
        "Pb": 99.0,
        "Fe": 0.0,
        "Ni": 0.0,
        "P": 0.0,
        "Mn": 0.0,
        "Si": 0.0,
        "Al": 0.0,
        "S": 0.0,
        "Cr": 0.0,
        "C": 0.0,
        "Mg": 0.0,
        "Ti": 0.0,
        "Mo": 0.0,
        "V": 0.0,
        "Nb": 0.0,
        "Sb": 0.0,
        "Ca": 0.0,
        "Cu": 0.0,
        "Material_Name": "LEAD",
        "Cost_Per_Kg": 690.0,
        "Category": "Virgin Metals & Additives",
        "Max_Stock_Kg": null
    },
    {
        "ID": 48,
        "Name": "NICKEL COPPER SCRAP (NI = 35%)",
        "Cost": 2450.0,
        "Sn": 0.0,
        "Zn": 0.3,
        "Pb": 0.0,
        "Fe": 1.0,
        "Ni": 32.5,
        "P": 0.0,
        "Mn": 0.5,
        "Si": 0.35,
        "Al": 0.0,
        "S": 0.0,
        "Cr": 0.3,
        "C": 0.125,
        "Mg": 0.0,
        "Ti": 0.0,
        "Mo": 0.0,
        "V": 0.0,
        "Nb": 0.0,
        "Sb": 0.0,
        "Ca": 0.0,
        "Cu": 63.0,
        "Material_Name": "NICKEL COPPER SCRAP (NI = 35%)",
        "Cost_Per_Kg": 2450.0,
        "Category": "Copper & Bronze",
        "Max_Stock_Kg": null
    },
    {
        "ID": 49,
        "Name": "NICKEL COPPER SCRAP (NI = 65%)",
        "Cost": 2700.0,
        "Sn": 0.0,
        "Zn": 0.275,
        "Pb": 0.0,
        "Fe": 0.9,
        "Ni": 65.0,
        "P": 0.0,
        "Mn": 0.45,
        "Si": 0.35,
        "Al": 0.0,
        "S": 0.0,
        "Cr": 0.275,
        "C": 0.115,
        "Mg": 0.0,
        "Ti": 0.0,
        "Mo": 0.0,
        "V": 0.0,
        "Nb": 0.0,
        "Sb": 0.0,
        "Ca": 0.0,
        "Cu": 33.0,
        "Material_Name": "NICKEL COPPER SCRAP (NI = 65%)",
        "Cost_Per_Kg": 2700.0,
        "Category": "Copper & Bronze",
        "Max_Stock_Kg": null
    },
    {
        "ID": 50,
        "Name": "NICKEL SCRAP - 100%",
        "Cost": 6000.0,
        "Sn": 0.0,
        "Zn": 0.0,
        "Pb": 0.0,
        "Fe": 0.0,
        "Ni": 99.5,
        "P": 0.0,
        "Mn": 0.0,
        "Si": 0.0,
        "Al": 0.0,
        "S": 0.0,
        "Cr": 0.0,
        "C": 0.0,
        "Mg": 0.0,
        "Ti": 0.0,
        "Mo": 0.0,
        "V": 0.0,
        "Nb": 0.0,
        "Sb": 0.0,
        "Ca": 0.0,
        "Cu": 0.0,
        "Material_Name": "NICKEL SCRAP - 100%",
        "Cost_Per_Kg": 6000.0,
        "Category": "Virgin Metals & Additives",
        "Max_Stock_Kg": null
    },
    {
        "ID": 51,
        "Name": "NICKEL VALVE SCRAP - 30%",
        "Cost": 900.0,
        "Sn": 0.0,
        "Zn": 0.0,
        "Pb": 0.0,
        "Fe": 47.5,
        "Ni": 30.0,
        "P": 0.0,
        "Mn": 2.0,
        "Si": 0.5,
        "Al": 0.0,
        "S": 0.0,
        "Cr": 17.5,
        "C": 0.275,
        "Mg": 0.0,
        "Ti": 0.0,
        "Mo": 1.5,
        "V": 0.0,
        "Nb": 0.0,
        "Sb": 0.0,
        "Ca": 0.0,
        "Cu": 1.0,
        "Material_Name": "NICKEL VALVE SCRAP - 30%",
        "Cost_Per_Kg": 900.0,
        "Category": "Stainless & High Alloy",
        "Max_Stock_Kg": null
    },
    {
        "ID": 52,
        "Name": "NICKEL VALVE SCRAP - 50%",
        "Cost": 1800.0,
        "Sn": 0.0,
        "Zn": 0.0,
        "Pb": 0.0,
        "Fe": 22.5,
        "Ni": 50.0,
        "P": 0.0,
        "Mn": 2.0,
        "Si": 1.0,
        "Al": 0.0,
        "S": 0.0,
        "Cr": 18.0,
        "C": 0.4,
        "Mg": 0.0,
        "Ti": 0.0,
        "Mo": 3.0,
        "V": 0.0,
        "Nb": 0.0,
        "Sb": 0.0,
        "Ca": 0.0,
        "Cu": 1.0,
        "Material_Name": "NICKEL VALVE SCRAP - 50%",
        "Cost_Per_Kg": 1800.0,
        "Category": "Stainless & High Alloy",
        "Max_Stock_Kg": null
    },
    {
        "ID": 53,
        "Name": "NICKEL VALVE SCRAP - 70%",
        "Cost": 3100.0,
        "Sn": 0.0,
        "Zn": 0.0,
        "Pb": 0.0,
        "Fe": 8.416,
        "Ni": 69.307,
        "P": 0.0,
        "Mn": 1.238,
        "Si": 0.99,
        "Al": 0.0,
        "S": 0.0,
        "Cr": 17.327,
        "C": 0.248,
        "Mg": 0.0,
        "Ti": 0.0,
        "Mo": 1.485,
        "V": 0.0,
        "Nb": 0.0,
        "Sb": 0.0,
        "Ca": 0.0,
        "Cu": 0.99,
        "Material_Name": "NICKEL VALVE SCRAP - 70%",
        "Cost_Per_Kg": 3100.0,
        "Category": "Stainless & High Alloy",
        "Max_Stock_Kg": null
    },
    {
        "ID": 54,
        "Name": "TIN",
        "Cost": 17000.0,
        "Sn": 99.5,
        "Zn": 0.0,
        "Pb": 0.0,
        "Fe": 0.0,
        "Ni": 0.0,
        "P": 0.0,
        "Mn": 0.0,
        "Si": 0.0,
        "Al": 0.0,
        "S": 0.0,
        "Cr": 0.0,
        "C": 0.0,
        "Mg": 0.0,
        "Ti": 0.0,
        "Mo": 0.0,
        "V": 0.0,
        "Nb": 0.0,
        "Sb": 0.0,
        "Ca": 0.0,
        "Cu": 0.0,
        "Material_Name": "TIN",
        "Cost_Per_Kg": 17000.0,
        "Category": "Virgin Metals & Additives",
        "Max_Stock_Kg": null
    },
    {
        "ID": 55,
        "Name": "ZINC",
        "Cost": 1270.0,
        "Sn": 0.0,
        "Zn": 99.25,
        "Pb": 0.0,
        "Fe": 0.0,
        "Ni": 0.0,
        "P": 0.0,
        "Mn": 0.0,
        "Si": 0.0,
        "Al": 0.0,
        "S": 0.0,
        "Cr": 0.0,
        "C": 0.0,
        "Mg": 0.0,
        "Ti": 0.0,
        "Mo": 0.0,
        "V": 0.0,
        "Nb": 0.0,
        "Sb": 0.0,
        "Ca": 0.0,
        "Cu": 0.0,
        "Material_Name": "ZINC",
        "Cost_Per_Kg": 1270.0,
        "Category": "Virgin Metals & Additives",
        "Max_Stock_Kg": null
    }
],
    presets: {
    "SS 304 (Austenitic Standard)": {
        "family": "stainless",
        "targets": {
            "C": [
                0.0,
                0.08
            ],
            "Cr": [
                18.0,
                20.0
            ],
            "Ni": [
                8.0,
                10.5
            ],
            "Mn": [
                0.5,
                2.0
            ],
            "Si": [
                0.2,
                1.0
            ],
            "P": [
                0.0,
                0.045
            ],
            "S": [
                0.0,
                0.03
            ]
        },
        "desc": "Standard 18/8 austenitic stainless steel for food, dairy, chemical & architectural casting."
    },
    "SS 316 (Marine & Acid Resistant)": {
        "family": "stainless",
        "targets": {
            "C": [
                0.0,
                0.08
            ],
            "Cr": [
                16.0,
                18.0
            ],
            "Ni": [
                10.0,
                14.0
            ],
            "Mo": [
                2.0,
                3.0
            ],
            "Mn": [
                0.5,
                2.0
            ],
            "Si": [
                0.2,
                1.0
            ],
            "P": [
                0.0,
                0.045
            ],
            "S": [
                0.0,
                0.03
            ]
        },
        "desc": "Molybdenum-bearing stainless grade with superior pitting & crevice corrosion resistance."
    },
    "SS 309 (26/12 Heat Resistant)": {
        "family": "stainless",
        "targets": {
            "C": [
                0.03,
                0.15
            ],
            "Cr": [
                22.0,
                24.0
            ],
            "Ni": [
                12.0,
                15.0
            ],
            "Mn": [
                0.5,
                2.0
            ],
            "Si": [
                0.5,
                1.5
            ]
        },
        "desc": "High chromium-nickel heat resistant alloy for furnace fixtures & boilers (up to 1000\u00b0C)."
    },
    "SS 310 (26/20 High Temp)": {
        "family": "stainless",
        "targets": {
            "C": [
                0.03,
                0.15
            ],
            "Cr": [
                24.0,
                26.0
            ],
            "Ni": [
                19.0,
                22.0
            ],
            "Mn": [
                0.5,
                2.0
            ],
            "Si": [
                0.5,
                1.5
            ]
        },
        "desc": "Severe high-temperature oxidation resistant casting alloy (up to 1150\u00b0C)."
    },
    "SS 420 (Martensitic Tool/Knife)": {
        "family": "stainless",
        "targets": {
            "C": [
                0.15,
                0.4
            ],
            "Cr": [
                12.0,
                14.0
            ],
            "Mn": [
                0.2,
                1.0
            ],
            "Si": [
                0.2,
                1.0
            ],
            "Ni": [
                0.0,
                0.75
            ]
        },
        "desc": "Hardenable martensitic stainless steel for valves, cutlery, and pump shafts."
    },
    "SS 430 (Ferritic Stainless)": {
        "family": "stainless",
        "targets": {
            "C": [
                0.0,
                0.12
            ],
            "Cr": [
                16.0,
                18.0
            ],
            "Mn": [
                0.2,
                1.0
            ],
            "Si": [
                0.2,
                1.0
            ],
            "Ni": [
                0.0,
                0.75
            ]
        },
        "desc": "Non-nickel ferritic stainless steel with good ductility and corrosion resistance."
    },
    "SS 201 (Low Nickel Economy)": {
        "family": "stainless",
        "targets": {
            "C": [
                0.0,
                0.15
            ],
            "Cr": [
                16.0,
                18.0
            ],
            "Ni": [
                3.5,
                5.5
            ],
            "Mn": [
                5.5,
                7.5
            ],
            "Cu": [
                1.0,
                3.0
            ],
            "Si": [
                0.2,
                1.0
            ]
        },
        "desc": "Austenitic grade substituting manganese and nitrogen for nickel."
    },
    "Grey Cast Iron (FG 200/250)": {
        "family": "cast_iron",
        "targets": {
            "C": [
                3.1,
                3.5
            ],
            "Si": [
                1.8,
                2.4
            ],
            "Mn": [
                0.5,
                0.9
            ],
            "P": [
                0.0,
                0.15
            ],
            "S": [
                0.0,
                0.12
            ]
        },
        "desc": "Class 30/35 flake graphite iron for machinery bases, pump housings, and manifolds."
    },
    "Ductile / SG Iron (GGG 40/50)": {
        "family": "cast_iron",
        "targets": {
            "C": [
                3.4,
                3.8
            ],
            "Si": [
                2.2,
                2.8
            ],
            "Mn": [
                0.2,
                0.5
            ],
            "Mg": [
                0.035,
                0.06
            ],
            "P": [
                0.0,
                0.05
            ],
            "S": [
                0.0,
                0.02
            ]
        },
        "desc": "Nodular spheroidal graphite iron with high tensile strength and elongation."
    },
    "High Chrome White Iron (25% Cr)": {
        "family": "cast_iron",
        "targets": {
            "C": [
                2.2,
                3.0
            ],
            "Cr": [
                23.0,
                27.0
            ],
            "Si": [
                0.8,
                1.5
            ],
            "Mn": [
                0.5,
                1.5
            ],
            "Mo": [
                0.5,
                1.5
            ]
        },
        "desc": "Abrasion-resistant martensitic white iron for slurry pumps, impellers and grinding liners."
    },
    "Mild Steel Cast (ASTM A216 WCB)": {
        "family": "steel",
        "targets": {
            "C": [
                0.18,
                0.25
            ],
            "Mn": [
                0.6,
                1.0
            ],
            "Si": [
                0.3,
                0.6
            ],
            "P": [
                0.0,
                0.04
            ],
            "S": [
                0.0,
                0.045
            ]
        },
        "desc": "Standard carbon steel casting for pressure valves, flanges, and structural brackets."
    },
    "Hadfield Manganese Steel (12-14% Mn)": {
        "family": "steel",
        "targets": {
            "C": [
                1.0,
                1.35
            ],
            "Mn": [
                11.5,
                14.0
            ],
            "Si": [
                0.3,
                0.8
            ],
            "Cr": [
                0.0,
                2.0
            ],
            "P": [
                0.0,
                0.07
            ]
        },
        "desc": "Severe work-hardening austenitic manganese steel for crusher jaws, hammers, and railway frogs."
    },
    "H-13 Die Steel (Hot Work)": {
        "family": "steel",
        "targets": {
            "C": [
                0.35,
                0.42
            ],
            "Cr": [
                4.8,
                5.5
            ],
            "Mo": [
                1.2,
                1.6
            ],
            "V": [
                0.8,
                1.2
            ],
            "Si": [
                0.8,
                1.2
            ],
            "Mn": [
                0.25,
                0.5
            ]
        },
        "desc": "Hot-work tool steel with excellent thermal fatigue cracking resistance."
    },
    "Bronze 555 (Leaded Gunmetal LG2)": {
        "family": "bronze",
        "targets": {
            "Cu": [
                82.0,
                87.0
            ],
            "Sn": [
                4.0,
                6.0
            ],
            "Zn": [
                4.0,
                6.0
            ],
            "Pb": [
                4.0,
                6.0
            ],
            "Ni": [
                0.0,
                1.0
            ],
            "P": [
                0.0,
                0.05
            ]
        },
        "desc": "Free-machining bearing bronze / gunmetal with good pressure tightness for valves and bushings."
    },
    "Tin Bronze (9-12% Sn Gear Bronze)": {
        "family": "bronze",
        "targets": {
            "Cu": [
                85.0,
                90.0
            ],
            "Sn": [
                9.0,
                12.0
            ],
            "Zn": [
                0.5,
                2.5
            ],
            "Pb": [
                0.5,
                2.5
            ],
            "P": [
                0.0,
                0.2
            ]
        },
        "desc": "Heavy-duty phosphor/tin bronze for high-load bearings, worm gears, and marine bushings."
    },
    "Custom Formulation": {
        "family": "custom",
        "targets": {
            "C": [
                0.1,
                0.3
            ],
            "Mn": [
                0.5,
                1.2
            ],
            "Si": [
                0.2,
                0.6
            ]
        },
        "desc": "Fully configurable custom foundry alloy specification."
    }
},
    recoveryFactors: {
    "C": 0.92,
    "Si": 0.88,
    "Mn": 0.88,
    "Cr": 0.95,
    "Ni": 0.99,
    "Mo": 0.98,
    "Cu": 0.98,
    "Fe": 0.97,
    "Al": 0.75,
    "Ti": 0.7,
    "Mg": 0.4,
    "P": 1.0,
    "S": 1.0,
    "Pb": 0.95,
    "Zn": 0.9,
    "Sn": 0.95,
    "V": 0.9,
    "Nb": 0.92,
    "Ca": 0.4,
    "Sb": 0.9
},
    ferrousTrampCaps: {
    "Pb": 0.015,
    "Sn": 0.03,
    "Zn": 0.02,
    "P": 0.045,
    "S": 0.035,
    "Cu": 0.6
},
    copperTrampCaps: {
    "Fe": 0.5,
    "Al": 0.5,
    "Si": 0.15,
    "P": 0.15
}
};
